import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img/>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam
            quae rerum reiciendis ipsum earum suscipit reprehenderit
            praesentium, debitis eius corrupti iure nemo delectus omnis aut
            asperiores exercitationem quasi consequatur expedita.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in San fransisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam
            quae rerum reiciendis ipsum earum suscipit reprehenderit
            praesentium, debitis eius corrupti iure nemo delectus omnis aut
            asperiores exercitationem quasi consequatur expedita.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam
            quae rerum reiciendis ipsum earum suscipit reprehenderit
            praesentium, debitis eius corrupti iure nemo delectus omnis aut
            asperiores exercitationem quasi consequatur expedita.
          </p>
        </a>
      </main>
    </>
  );
}
