import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import HomePage from "@/components/home/home-page";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}
// this function will only run on the server side not on the client side
// always export as an stand alone function
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json"); // requesting on the events_categories data from the data.json file

  return {
    props: {
      data: events_categories,
    },
  };
}


